language: python

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libevent-dev libev-dev
 - pip install https://bitbucket.org/eriks5/gevent-subprocess/get/tip.tar.gz

python:
  - "2.6"
  - "2.7"

install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements_dev.txt --use-mirrors
  - python setup.py install

script:
  - python setup.py test
  - python tests/run_autobahn_tests.py
